name: owntone_sync
description: "Sync playlists from OwnTone server to Android device"
publish_to: 'none'

version: 0.1.8+17

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.7.0

  # Local database
  sqflite: ^2.4.1

  # File system access
  path_provider: ^2.1.5
  path: ^1.9.0

  # State management
  provider: ^6.1.2

  # Background work (for scheduled syncs)
  workmanager: ^0.9.0+3

  # JSON serialization
  json_annotation: ^4.9.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4

  # Internationalization for date formatting
  intl: ^0.20.0

  # Logging
  logger: ^2.0.0

  # Audio playback
  just_audio: ^0.10.6
  audio_service: ^0.18.13
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation for JSON
  build_runner: ^2.10.0
  json_serializable: ^6.11.0

  # Iconography
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon-1024.png"
  adaptive_icon_background: "#37474f"
  adaptive_icon_foreground: "assets/images/fg.png"
  adaptive_icon_monochrome: "assets/images/monochrome.png"